
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

import type { FirebaseOptions } from 'firebase/app';

// Your web app's Firebase configuration
export const firebaseConfig: FirebaseOptions = {
  apiKey: "API_KEY",
  authDomain: "AUTH_DOMAIN",
  projectId: "PROJECT_ID",
  storageBucket: "STORAGE_BUCKET",
  messagingSenderId: "MESSAGING_SENDER_ID",
  appId: "APP_ID",
};
